# 错误和异常

到异常处理并不会导致代码混乱，而添加大量的if语句来检查各种可能的错误状态将导致代码的可读性极差。

## 一些内置的异常类
* Exception 几乎所有的异常类都是从它派生而来的
* AttributeError 引用属性或给它赋值失败时引发
* OSError 操作系统不能执行指定的任务（如打开文件）时引发，有多个子类
* IndexError 使用序列中不存在的索引时引发，为LookupError的子类
* KeyError 使用映射中不存在的键时引发，为LookupError的子类
* NameError 找不到名称（变量）时引发
* SyntaxError 代码不正确时引发
* TypeError 将内置操作或函数用于类型不正确的对象时引发
* ValueError 将内置操作或函数用于这样的对象时引发：其类型正确但包含的值不合适
* ZeroDivisionError 在除法或求模运算的第二个参数为零时引发
* IOError 输入输出异常
* ImportError 无法引入模块或包，基本是路径问题
* IndentationError 语法错误，代码没有正确的对齐


断言跟异常的区别：
* 断言是用来检查非法情况而不是错误情况的，用来帮开发者快速定位问题的位置。
* 异常处理用于对程序发生异常情况的处理，增强程序的健壮性和容错性


-----------------------------------------------------------------------------------

## 错误和异常的概念


错误
* 错误和异常的概念
* 常见的错误
* 异常处理
    - try-except及else/finally
    - 截获异常
    - try-finally
    - 异常处理的综合使用
* with-as语句与上下文管理
* 标准异常和自定义异常
* raise和assert


### 错误
* 语法错误：代码不符合解释器或编译器语法
* 逻辑错误： 不完整或不合法输入或者计算出现问题

### 异常
执行过程中出现问题导致程序无法执行
* 程序遇到逻辑或算法问题
* 运行过程中计算机错误（内存不够或IO错误）

### 错误和异常的区别
错误
* 代码运行前的语法或逻辑错误
* 语法错误在执行前修改，逻辑错误无法修改

异常分为两个步骤
* 异常产生，检查到错误且解释器认为是异常，抛出异常
* 异常处理，截获异常，忽略或终止程序处理异常

### 常见错误（ipython）
* NameError
* SyntaxError
* IOError
* ZeroDivisionError
* ValueError







-----------------------------------------------------------------------------------

## 错误和异常的处理 - with-as


### with语句
Usage::
```py
with context [as var]:
    with_block
```
* with语句用来代替try-except-finally，使代码更加简洁。
* context表达式返回的是一个对象
* var用来保存context返回对象，单个返回值或元组
* with_suit使用var变量来对context返回的对象进行操作


```py
with open("1.txt") as f:
    for lien in f.readlines():
        print(line)
```
* 打开1.txt文件
* f接受的是由open返回的文件对象，文件为1.txt
* with中的代码执行完成后，文件将会被自动关闭


### with explanations
* 上下文管理协议：包含的方法为__enter__()和__exit__()，支持该协议的对象要实现这两个方法
* 上下文管理器：定义执行with语句时要建立的运行时上下文，负责执行with语句上下文中的进入和退出操作
* 进入上下文管理器：调用管理器__enter__方法，如果设置as var语句，var变量接受__enter__()方法返回的值
* 退出上下文管理器：调用管理器__exit__方法


```py
class Mycontext(object):
    def __init__(self, name):
        self.name = name
    
    def __enter__(self):
        print('__enter__')
        return self
    
    def do_sth(self):
        print("do sth")

    def __exit__(self, exc_type, exc_value, traceback):
        print("__exit__")
        print(f"Error {exc_type}, info {exc_value}")

if __name__ == "__main__":
    with Mycontext('test context') as f:
        print(f.name)
        f.do_sth()
```

### with 应用场景
* 文件操作
* 进程线程之间互斥现象，如互斥锁
* 支持上下文的其他对象




-----------------------------------------------------------------------------------

## 错误和异常的处理 - raise

主要用于主动抛出异常

raise [Exception [, args]]
* Exception: 异常类
* args： 描述异常信息的元组



-----------------------------------------------------------------------------------

## 错误和异常的处理 - assert

断言语句：assert语句用于检测表达式是否为真，如果为假，引发AssertionError错误

assert expression [,args]
* exception：表达式
* args： 判断条件的描述信息


-----------------------------------------------------------------------------------

## 标准异常

python内奸异常，程序执行前就已经存在

BaseException（所有异常基类）
* KeyboardInterrupt（用户终端Ctrl + c）
* Exception（常见错误的基类）
    - SyntaxError
    - NameError
    - IOError
    - ImportError
    - ...
* SystemExit（Python解释器退出）




-----------------------------------------------------------------------------------

## 自定义异常

* Python允许自定义异常，用于描述Python中没有涉及的异常情况
* 自定义异常必须继承Exception类
* 自定义异常只能主动触发


```py
class CustomError(Exception):
    def __init__(self, info):
        Exception.__init__(self)
        self.info = info

    def __str__(self):
        return f"CustomError {self.info}"

try:
    raise CustomError("test custom error")
except CustomError as e:
    print(f"Error info {e}")
```


```py
class CustomError(Exception):
    def __init__(self, info):
        Exception.__init__(self)
        self.info = info
        print(id(self))

    def __str__(self):
        return f"CustomError {self.info}"

try:
    raise CustomError("test custom error")
except CustomError as e:
    print(f"Obj ID {id(e)}, Error info {e}")
```
